# Generated by Django 4.0.1 on 2022-01-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dis_logic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountOff',
        ),
    ]
